os: linux
sudo: required
language: r
before_install:
- tlmgr install index simplewick
apt_packages:
- pdf2djvu
script:
- pdflatex -interaction=nonstopmode beyond.tex
deploy:
  provider: releases
  api_key:
    secure: oNJUkDRl3fTQgk8/j3PlwH7srGQYjW0ng9ZU/sSmZo9E9jhBEF6FR0ky9kREQMmu/bbHWPfZLKqMtIuGl/wW71q/gAV0AKT/sH+DZ269VJtmjR1KEj8VNEJ0RE+rBGQ/CD36MkXtwipCxuUg14U7PrOIapVPkUPpyr1gx0ozQIkbE3b+K468yIVHkR9pfiYkuJWvr7ezunkM6RltnJA13733FUj/4U+qaNEWcKD8FGh5E8l68Zz/hzzEMm4aFkPn4XEqaJuaMN/Kqm82O9LwALYN7pTvCj6par4OQ1Z+dx/sujKRjRyhFMIcv14QpxYA4FBoH06bxk+Y8x3hP/X1+aqfY6b9C4Z6m1IRSLObXwC/Nu3gsG+OnNsCCwzpwdjQYk8mgnXe+QR903jq03w3UveYPkR1hPGNMrMDsAO8oOcr98S0wpIzcxshVzBO2EQzDE7gidA3C9wjZprzW5PBc7hEtPWkv0Kh0hl1cGvQ7dYqn+uYPEJgvA8XsMyF3yEUYutSIGVcWTK2rDodPqNE6fdiLQUfUyoc3XAQhf4hh8k4b6wpSOrBqKiTrjSchdHAT+GalSfXP4RwKE3SjXIl5K2ir62XU+CmRxq1jg7zqNW5gNiHjqzQqarxjIRmriPm3Em2nySHWRFgM+Nsy4680NXf5EhX9HheIOFwdsczBeI=
  file: beyond.pdf
  on:
    repo: restrepo/beyond-the-standard-model
